# Can't catch DoesNotExist exception with Django 1.8 and Python 3.4
url = ...
response = self.client.get(url)
