# Python - Python 3.1 can't seem to handle UTF-16 encoded files?
open(bla, 'r', encoding="utf-16")
