# How do I inspect the scope of a function where Python raises an exception?
&gt;&gt;&gt; import pdb
&gt;&gt;&gt; pdb.pm()
