# Internal Error on trying copy data to postgres table from python code using copy_from function of psycopg2
connection.rollback()
