# Exception statement not covered by self.assertRaises in python unit test cases
self.assertRaises(Exception, helpers.get_value, m, 'start_date')
