# Probleme with custom user Django
manage.py syncdb
